using System.Collections.Generic;

namespace NowPlaying
{
    public static class GlobalVariables
    {
        public static readonly Dictionary<string, string> Ru2En = new Dictionary<string, string>
        {
            { "ё", "yo"},
            { "ж", "zh"},
            { "ч", "ch"},
            { "ш", "sh"},
            { "щ", "sch"},
            { "ю", "yu"},
            { "я", "ya"},
            { "Ё", "Yo"},
            { "Ж", "Zh"},
            { "Ч", "Ch"},
            { "Ш", "Sh"},
            { "Щ", "Sch"},
            { "Ю", "Yu"},
            { "Я", "Ya"},
            { "а", "a"},
            { "б", "b"},
            { "в", "v"},
            { "г", "g"},
            { "д", "d"},
            { "е", "e"},
            { "з", "z"},
            { "и", "i"},
            { "й", "j"},
            { "к", "k"},
            { "л", "l"},
            { "м", "m"},
            { "н", "n"},
            { "о", "o"},
            { "п", "p"},
            { "р", "r"},
            { "с", "s"},
            { "т", "t"},
            { "у", "u"},
            { "ф", "f"},
            { "х", "h"},
            { "ц", "c"},
            { "ъ", "j"},
            { "ы", "i"},
            { "ь", "j"},
            { "э", "e"},
            { "А", "A"},
            { "Б", "B"},
            { "В", "V"},
            { "Г", "G"},
            { "Д", "D"},
            { "Е", "E"},
            { "З", "Z"},
            { "И", "I"},
            { "Й", "J"},
            { "К", "K"},
            { "Л", "L"},
            { "М", "M"},
            { "Н", "N"},
            { "О", "O"},
            { "П", "P"},
            { "Р", "R"},
            { "С", "S"},
            { "Т", "T"},
            { "У", "U"},
            { "Ф", "F"},
            { "Х", "H"},
            { "Ц", "C"},
            { "Ъ", "J"},
            { "Ы", "I"},
            { "Ь", "J"},
            { "Э", "E"}
        };

        public static List<string> SourceEngineAllowedKeys = new List<string>() //todo
        {
            {""},
            {"space"},
            {"capslock"},
            {"escape"},
            {"f1"},
            {"f2"},
            {"f3"},
            {"f4"},
            {"f5"},
            {"f6"},
            {"f7"},
            {"f8"},
            {"f9"},
            {"f10"},
            {"f11"},
            {"f12"},
            {"pause"},
            {"`"},
            {"-"},
            {"="},
            {"backspace"},
            {"tab"},
            {"]"},
            {"["},
            {"/"},
            {"semicolon"},
            {"'"},
            {"\\"},
            {"shift"},
            {"enter"},
            {","},
            {"ctrl"},
            {"alt"},
            {"1"},
            {"2"},
            {"3"},
            {"4"},
            {"5"},
            {"6"},
            {"7"},
            {"8"},
            {"9"},
            {"0"},
            {"a"},
            {"b"},
            {"c"},
            {"d"},
            {"e"},
            {"f"},
            {"g"},
            {"h"},
            {"i"},
            {"j"},
            {"k"},
            {"l"},
            {"m"},
            {"n"},
            {"o"},
            {"p"},
            {"q"},
            {"r"},
            {"s"},
            {"t"},
            {"u"},
            {"v"},
            {"w"},
            {"x"},
            {"y"},
            {"z"},
            {"uparrow"},
            {"downarrow"},
            {"rightarrow"},
            {"leftarrow"},
            {"ins"},
            {"home"},
            {"pgup"},
            {"pgdn"},
            {"del"},
            {"end"},
            {"mouse1"},
            {"mouse2"},
            {"mouse3"},
            {"mouse4"},
            {"mouse5"},
            {"mwheelup"},
            {"mwheeldown"},
            {"kp_end"},
            {"kp_downarrow"},
            {"kp_pgdn"},
            {"kp_leftarrow"},
            {"kp_5"},
            {"kp_rightarrow"},
            {"kp_home"},
            {"kp_uparrow"},
            {"kp_pgup"},
            {"kp_ins"},
            {"kp_plus "},
            {"kp_minus"},
            {"kp_slash"},
            {"kp_del"},
            {"*"},
            {"kp_enter"}
        };
    }
}