using System.Collections.Generic;

namespace NowPlaying
{
    public class KeyFormatter
    {
        public KeySender.ScanCodeShort GetKey(string Key)
        {
            KeyValuePairs.TryGetValue(Key, out KeySender.ScanCodeShort KeyCode);
            return KeyCode;
        }

        public KeySender.VirtualKeyShort GetVirtualKey(string Key)
        {
            VirtualKeyValuePairs.TryGetValue(Key, out KeySender.VirtualKeyShort KeyCode);
            return KeyCode;
        }

        public Dictionary<string, KeySender.ScanCodeShort> KeyValuePairs = new Dictionary<string, KeySender.ScanCodeShort>
        {
          //{""},
            {"space", KeySender.ScanCodeShort.SPACE},
          //{"capslock"},
            {"escape", KeySender.ScanCodeShort.ESCAPE},
            {"kp_5", KeySender.ScanCodeShort.NUMPAD5},
            {"w", KeySender.ScanCodeShort.KEY_W},
            {"f1", KeySender.ScanCodeShort.F1},
            {"f2", KeySender.ScanCodeShort.F2},
            {"f3", KeySender.ScanCodeShort.F3},
            {"f4", KeySender.ScanCodeShort.F4},
            {"f5", KeySender.ScanCodeShort.F5},
            {"f6", KeySender.ScanCodeShort.F6},
            {"f7", KeySender.ScanCodeShort.F7},
            {"f8", KeySender.ScanCodeShort.F8},
            {"f9", KeySender.ScanCodeShort.F9},
            {"f10", KeySender.ScanCodeShort.F10},
            {"f11", KeySender.ScanCodeShort.F11},
            {"f12", KeySender.ScanCodeShort.F12},
            {"pause", KeySender.ScanCodeShort.PAUSE},
            //{"`"},
            {"-", KeySender.ScanCodeShort.OEM_MINUS},
            //{"=", KeySender.ScanCodeShort.},
            //{"backspace", },
            {"tab", KeySender.ScanCodeShort.TAB},
            //{"]"},
            //{"["},
            //{"/"},
            //{"semicolon"},
            //{"'"},
            //{"\\"},
            //{"shift"},
            //{"enter"},
            //{","},
            //{"ctrl"},
            //{"alt"},
            {"1", KeySender.ScanCodeShort.KEY_1},
            {"2", KeySender.ScanCodeShort.KEY_2},
            {"3", KeySender.ScanCodeShort.KEY_3},
            {"4", KeySender.ScanCodeShort.KEY_4},
            {"5", KeySender.ScanCodeShort.KEY_5},
            {"6", KeySender.ScanCodeShort.KEY_6},
            {"7", KeySender.ScanCodeShort.KEY_7},
            {"8", KeySender.ScanCodeShort.KEY_8},
            {"9", KeySender.ScanCodeShort.KEY_9},
            {"0", KeySender.ScanCodeShort.KEY_0},
            {"a", KeySender.ScanCodeShort.KEY_A},
            {"b", KeySender.ScanCodeShort.KEY_B},
            {"c", KeySender.ScanCodeShort.KEY_C},
            {"d", KeySender.ScanCodeShort.KEY_D},
            {"e", KeySender.ScanCodeShort.KEY_E},
            {"f", KeySender.ScanCodeShort.KEY_F},
            {"g", KeySender.ScanCodeShort.KEY_G},
            {"h", KeySender.ScanCodeShort.KEY_H},
            {"i", KeySender.ScanCodeShort.KEY_I},
            {"j", KeySender.ScanCodeShort.KEY_J},
            {"k", KeySender.ScanCodeShort.KEY_K},
            {"l", KeySender.ScanCodeShort.KEY_L},
            {"m", KeySender.ScanCodeShort.KEY_M},
            {"n", KeySender.ScanCodeShort.KEY_N},
            {"o", KeySender.ScanCodeShort.KEY_O},
            {"p", KeySender.ScanCodeShort.KEY_P},
            {"q", KeySender.ScanCodeShort.KEY_Q},
            {"r", KeySender.ScanCodeShort.KEY_R},
            {"s", KeySender.ScanCodeShort.KEY_S},
            {"t", KeySender.ScanCodeShort.KEY_T},
            {"u", KeySender.ScanCodeShort.KEY_U},
            {"v", KeySender.ScanCodeShort.KEY_V},
            {"x", KeySender.ScanCodeShort.KEY_X},
            {"y", KeySender.ScanCodeShort.KEY_Y},
            {"z", KeySender.ScanCodeShort.KEY_Z},
            {"uparrow", KeySender.ScanCodeShort.UP},
            {"downarrow", KeySender.ScanCodeShort.DOWN},
            {"rightarrow", KeySender.ScanCodeShort.RIGHT},
            {"leftarrow", KeySender.ScanCodeShort.LEFT},
            {"ins", KeySender.ScanCodeShort.INSERT},
            {"home", KeySender.ScanCodeShort.HOME},
            //{"pgup"},
            //{"pgdn"},
            {"del", KeySender.ScanCodeShort.DELETE},
            {"end", KeySender.ScanCodeShort.END},
            //{"mouse1"},
            //{"mouse2"},
            //{"mouse3"},
            //{"mouse4"},
            //{"mouse5"},
            //{"mwheelup"},
            //{"mwheeldown"},
            {"kp_end", KeySender.ScanCodeShort.NUMPAD1},
            {"kp_downarrow", KeySender.ScanCodeShort.NUMPAD2},
            {"kp_pgdn", KeySender.ScanCodeShort.NUMPAD3},
            {"kp_leftarrow", KeySender.ScanCodeShort.NUMPAD4},
            {"kp_rightarrow", KeySender.ScanCodeShort.NUMPAD6},
            {"kp_home", KeySender.ScanCodeShort.NUMPAD7},
            {"kp_uparrow", KeySender.ScanCodeShort.NUMPAD8},
            {"kp_pgup", KeySender.ScanCodeShort.NUMPAD9},
            {"kp_ins", KeySender.ScanCodeShort.NUMPAD0},
            {"kp_plus", KeySender.ScanCodeShort.OEM_PLUS},
            {"kp_minus", KeySender.ScanCodeShort.OEM_MINUS}
            //{"kp_slash"},
            //{"kp_del", KeySender.ScanCodeShort.},
            //{"*"},
            //{"kp_enter"}
        };

        public static Dictionary<string, KeySender.VirtualKeyShort> VirtualKeyValuePairs = new Dictionary<string, KeySender.VirtualKeyShort>
        {
          //{"", null},
            {"space", KeySender.VirtualKeyShort.SPACE},
          //{"capslock", null},
            {"escape", KeySender.VirtualKeyShort.ESCAPE},
            {"kp_5", KeySender.VirtualKeyShort.NUMPAD5},
            {"w", KeySender.VirtualKeyShort.KEY_W},
            {"f1", KeySender.VirtualKeyShort.F1},
            {"f2", KeySender.VirtualKeyShort.F2},
            {"f3", KeySender.VirtualKeyShort.F3},
            {"f4", KeySender.VirtualKeyShort.F4},
            {"f5", KeySender.VirtualKeyShort.F5},
            {"f6", KeySender.VirtualKeyShort.F6},
            {"f7", KeySender.VirtualKeyShort.F7},
            {"f8", KeySender.VirtualKeyShort.F8},
            {"f9", KeySender.VirtualKeyShort.F9},
            {"f10", KeySender.VirtualKeyShort.F10},
            {"f11", KeySender.VirtualKeyShort.F11},
            {"f12", KeySender.VirtualKeyShort.F12},
            {"pause", KeySender.VirtualKeyShort.PAUSE},
            //{"`"},
            {"-", KeySender.VirtualKeyShort.OEM_MINUS},
            //{"=", KeySender.VirtualKeyShort.},
            //{"backspace", },
            {"tab", KeySender.VirtualKeyShort.TAB},
            //{"]"},
            //{"["},
            //{"/"},
            //{"semicolon"},
            //{"'"},
            //{"\\"},
            //{"shift"},
            //{"enter"},
            //{","},
            //{"ctrl"},
            //{"alt"},
            {"1", KeySender.VirtualKeyShort.KEY_1},
            {"2", KeySender.VirtualKeyShort.KEY_2},
            {"3", KeySender.VirtualKeyShort.KEY_3},
            {"4", KeySender.VirtualKeyShort.KEY_4},
            {"5", KeySender.VirtualKeyShort.KEY_5},
            {"6", KeySender.VirtualKeyShort.KEY_6},
            {"7", KeySender.VirtualKeyShort.KEY_7},
            {"8", KeySender.VirtualKeyShort.KEY_8},
            {"9", KeySender.VirtualKeyShort.KEY_9},
            {"0", KeySender.VirtualKeyShort.KEY_0},
            {"a", KeySender.VirtualKeyShort.KEY_A},
            {"b", KeySender.VirtualKeyShort.KEY_B},
            {"c", KeySender.VirtualKeyShort.KEY_C},
            {"d", KeySender.VirtualKeyShort.KEY_D},
            {"e", KeySender.VirtualKeyShort.KEY_E},
            {"f", KeySender.VirtualKeyShort.KEY_F},
            {"g", KeySender.VirtualKeyShort.KEY_G},
            {"h", KeySender.VirtualKeyShort.KEY_H},
            {"i", KeySender.VirtualKeyShort.KEY_I},
            {"j", KeySender.VirtualKeyShort.KEY_J},
            {"k", KeySender.VirtualKeyShort.KEY_K},
            {"l", KeySender.VirtualKeyShort.KEY_L},
            {"m", KeySender.VirtualKeyShort.KEY_M},
            {"n", KeySender.VirtualKeyShort.KEY_N},
            {"o", KeySender.VirtualKeyShort.KEY_O},
            {"p", KeySender.VirtualKeyShort.KEY_P},
            {"q", KeySender.VirtualKeyShort.KEY_Q},
            {"r", KeySender.VirtualKeyShort.KEY_R},
            {"s", KeySender.VirtualKeyShort.KEY_S},
            {"t", KeySender.VirtualKeyShort.KEY_T},
            {"u", KeySender.VirtualKeyShort.KEY_U},
            {"v", KeySender.VirtualKeyShort.KEY_V},
            {"x", KeySender.VirtualKeyShort.KEY_X},
            {"y", KeySender.VirtualKeyShort.KEY_Y},
            {"z", KeySender.VirtualKeyShort.KEY_Z},
            {"uparrow", KeySender.VirtualKeyShort.UP},
            {"downarrow", KeySender.VirtualKeyShort.DOWN},
            {"rightarrow", KeySender.VirtualKeyShort.RIGHT},
            {"leftarrow", KeySender.VirtualKeyShort.LEFT},
            {"ins", KeySender.VirtualKeyShort.INSERT},
            {"home", KeySender.VirtualKeyShort.HOME},
            //{"pgup"},
            //{"pgdn"},
            {"del", KeySender.VirtualKeyShort.DELETE},
            {"end", KeySender.VirtualKeyShort.END},
            //{"mouse1"},
            //{"mouse2"},
            //{"mouse3"},
            //{"mouse4"},
            //{"mouse5"},
            //{"mwheelup"},
            //{"mwheeldown"},
            {"kp_end", KeySender.VirtualKeyShort.NUMPAD1},
            {"kp_downarrow", KeySender.VirtualKeyShort.NUMPAD2},
            {"kp_pgdn", KeySender.VirtualKeyShort.NUMPAD3},
            {"kp_leftarrow", KeySender.VirtualKeyShort.NUMPAD4},
            {"kp_rightarrow", KeySender.VirtualKeyShort.NUMPAD6},
            {"kp_home", KeySender.VirtualKeyShort.NUMPAD7},
            {"kp_uparrow", KeySender.VirtualKeyShort.NUMPAD8},
            {"kp_pgup", KeySender.VirtualKeyShort.NUMPAD9},
            {"kp_ins", KeySender.VirtualKeyShort.NUMPAD0},
            {"kp_plus", KeySender.VirtualKeyShort.OEM_PLUS},
            {"kp_minus", KeySender.VirtualKeyShort.OEM_MINUS}
            //{"kp_slash"},
            //{"kp_del", KeySender.VirtualKeyShort.},
            //{"*"},
            //{"kp_enter"}
        };
    }
}
